use crate::model::{Rule, Site};
use std::collections::{HashMap, HashSet};
use std::fmt::Write;

const ADMIN_ADDR: &str = "localhost:2019";

/// Render a Caddyfile for the given sites.
///
/// `loop_resolver` is consulted when a proxy rule's target host is one of the
/// Bellboy-managed site domains — in that case we need the real external IP to
/// avoid the /etc/hosts loopback. Returning `None` falls back to the original
/// hostname (which will loop at runtime, but we'd rather emit *something*
/// than silently drop the rule).
pub fn generate<F>(sites: &[Site], loop_resolver: F) -> String
where
    F: Fn(&str) -> Option<String>,
{
    let managed: HashSet<&str> = sites
        .iter()
        .filter(|s| s.enabled)
        .map(|s| s.domain.as_str())
        .collect();

    let mut out = String::new();
    out.push_str("# Generated by Bellboy — changes will be overwritten.\n");
    let _ = writeln!(out, "{{\n\tadmin {}\n}}\n", ADMIN_ADDR);

    // Pre-resolve any managed-domain targets so we only call the resolver once
    // per host even if it's referenced from multiple rules.
    let mut resolved: HashMap<String, Option<String>> = HashMap::new();
    for site in sites.iter().filter(|s| s.enabled) {
        for rule in &site.rules {
            if let Rule::Proxy { target, .. } = rule {
                let host = parse_target(target).host;
                if managed.contains(host.as_str()) && !resolved.contains_key(&host) {
                    resolved.insert(host.clone(), loop_resolver(&host));
                }
            }
        }
    }

    for site in sites.iter().filter(|s| s.enabled) {
        render_site(&mut out, site, &managed, &resolved);
        out.push('\n');
    }
    out
}

fn render_site(
    out: &mut String,
    site: &Site,
    managed: &HashSet<&str>,
    resolved: &HashMap<String, Option<String>>,
) {
    let _ = writeln!(out, "{} {{", site.domain);
    // Every Bellboy-managed domain is local-only (127.0.0.1 via /etc/hosts).
    // Force Caddy's internal CA so it never tries Let's Encrypt for these.
    out.push_str("\ttls internal\n");

    for rule in &site.rules {
        render_rule(out, rule, managed, resolved);
    }

    out.push_str("\thandle {\n");
    let _ = writeln!(out, "\t\treverse_proxy {}", site.upstream);
    out.push_str("\t}\n");
    out.push_str("}\n");
}

fn render_rule(
    out: &mut String,
    rule: &Rule,
    managed: &HashSet<&str>,
    resolved: &HashMap<String, Option<String>>,
) {
    match rule {
        Rule::Proxy { path, target, .. } => render_proxy(out, path, target, managed, resolved),
        Rule::Static { path, root } => {
            let _ = writeln!(out, "\thandle {} {{", path);
            let _ = writeln!(out, "\t\troot * {}", root);
            out.push_str("\t\tfile_server\n");
            out.push_str("\t}\n");
        }
        Rule::Bypass { path } => {
            let _ = writeln!(out, "\thandle {} {{", path);
            out.push_str("\t\trespond 404\n");
            out.push_str("\t}\n");
        }
    }
}

fn render_proxy(
    out: &mut String,
    path: &str,
    target: &str,
    managed: &HashSet<&str>,
    resolved: &HashMap<String, Option<String>>,
) {
    let parsed = parse_target(target);
    let _ = writeln!(out, "\thandle {} {{", path);

    if managed.contains(parsed.host.as_str()) {
        // Loop-avoidance mode: the target host matches a Bellboy-managed domain
        // which is pinned to 127.0.0.1 in /etc/hosts. We substitute the real
        // external IP (resolved out-of-band) and preserve the original Host
        // header / SNI so the upstream keeps routing correctly.
        let scheme = if parsed.scheme.is_empty() {
            "https://"
        } else {
            parsed.scheme.as_str()
        };
        let ip = resolved
            .get(&parsed.host)
            .and_then(|v| v.clone())
            .unwrap_or_else(|| parsed.host.clone());
        let host_port = match &parsed.port {
            Some(p) => format!("{}:{}", ip, p),
            None => ip,
        };
        let _ = writeln!(out, "\t\treverse_proxy {}{} {{", scheme, host_port);
        let _ = writeln!(out, "\t\t\theader_up Host {}", parsed.host);
        out.push_str("\t\t\ttransport http {\n");
        let _ = writeln!(out, "\t\t\t\ttls_server_name {}", parsed.host);
        out.push_str("\t\t\t}\n");
        out.push_str("\t\t}\n");
    } else {
        let _ = writeln!(out, "\t\treverse_proxy {}", target);
    }

    out.push_str("\t}\n");
}

#[derive(Debug, PartialEq, Eq)]
struct ParsedTarget {
    scheme: String,
    host: String,
    port: Option<String>,
}

fn parse_target(target: &str) -> ParsedTarget {
    let (scheme, rest) = if let Some(r) = target.strip_prefix("https://") {
        ("https://", r)
    } else if let Some(r) = target.strip_prefix("http://") {
        ("http://", r)
    } else {
        ("", target)
    };
    // Drop any path segment — Caddy reverse_proxy targets don't carry paths.
    let rest = rest.split('/').next().unwrap_or(rest);
    let (host, port) = match rest.rsplit_once(':') {
        Some((h, p)) if !h.is_empty() && p.chars().all(|c| c.is_ascii_digit()) => {
            (h.to_string(), Some(p.to_string()))
        }
        _ => (rest.to_string(), None),
    };
    ParsedTarget {
        scheme: scheme.to_string(),
        host,
        port,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_site() -> Site {
        Site {
            id: "id".into(),
            domain: "myapp.test".into(),
            upstream: "localhost:3000".into(),
            enabled: true,
            rules: vec![
                Rule::Proxy {
                    path: "/api/*".into(),
                    target: "localhost:8080".into(),
                    envs: vec![],
                },
                Rule::Static {
                    path: "/static/*".into(),
                    root: "/Users/me/public".into(),
                },
                Rule::Bypass {
                    path: "/admin/*".into(),
                },
            ],
        }
    }

    fn no_resolver(_: &str) -> Option<String> {
        None
    }

    #[test]
    fn disabled_sites_excluded() {
        let mut site = sample_site();
        site.enabled = false;
        let out = generate(&[site], no_resolver);
        assert!(!out.contains("myapp.test {"));
    }

    #[test]
    fn rules_render_in_order() {
        let out = generate(&[sample_site()], no_resolver);
        let api_idx = out.find("/api/*").expect("proxy rule");
        let static_idx = out.find("/static/*").expect("static rule");
        let admin_idx = out.find("/admin/*").expect("bypass rule");
        let default_idx = out.find("reverse_proxy localhost:3000").expect("default");
        assert!(api_idx < static_idx);
        assert!(static_idx < admin_idx);
        assert!(admin_idx < default_idx);
    }

    #[test]
    fn admin_api_enabled() {
        let out = generate(&[], no_resolver);
        assert!(out.contains("admin localhost:2019"));
    }

    #[test]
    fn tls_internal_on_every_site() {
        let out = generate(&[sample_site()], no_resolver);
        assert!(out.contains("tls internal"));
    }

    #[test]
    fn self_loop_target_uses_resolved_ip() {
        let site = Site {
            id: "1".into(),
            domain: "dev.lfind.io.kr".into(),
            upstream: "localhost:3000".into(),
            enabled: true,
            rules: vec![Rule::Proxy {
                path: "/api/*".into(),
                target: "dev.lfind.io.kr".into(),
                envs: vec![],
            }],
        };
        let resolver = |h: &str| {
            assert_eq!(h, "dev.lfind.io.kr");
            Some("203.0.113.42".to_string())
        };
        let out = generate(&[site], resolver);
        assert!(out.contains("reverse_proxy https://203.0.113.42 {"));
        assert!(out.contains("header_up Host dev.lfind.io.kr"));
        assert!(out.contains("tls_server_name dev.lfind.io.kr"));
    }

    #[test]
    fn self_loop_target_preserves_port_and_scheme() {
        let site = Site {
            id: "1".into(),
            domain: "app.test".into(),
            upstream: "localhost:3000".into(),
            enabled: true,
            rules: vec![Rule::Proxy {
                path: "/api/*".into(),
                target: "http://app.test:8443".into(),
                envs: vec![],
            }],
        };
        let out = generate(&[site], |_| Some("10.0.0.9".to_string()));
        assert!(out.contains("reverse_proxy http://10.0.0.9:8443 {"));
    }

    #[test]
    fn self_loop_falls_back_to_hostname_when_resolve_fails() {
        let site = Site {
            id: "1".into(),
            domain: "app.test".into(),
            upstream: "localhost:3000".into(),
            enabled: true,
            rules: vec![Rule::Proxy {
                path: "/api/*".into(),
                target: "app.test".into(),
                envs: vec![],
            }],
        };
        let out = generate(&[site], |_| None);
        // Still renders the loop-avoidance structure (Host / SNI) so the user
        // sees a meaningful config; runtime will error loudly instead of
        // silently misbehaving.
        assert!(out.contains("header_up Host app.test"));
        assert!(out.contains("reverse_proxy https://app.test {"));
    }

    #[test]
    fn non_managed_target_uses_simple_proxy() {
        let site = Site {
            id: "1".into(),
            domain: "app.test".into(),
            upstream: "localhost:3000".into(),
            enabled: true,
            rules: vec![Rule::Proxy {
                path: "/api/*".into(),
                target: "localhost:8080".into(),
                envs: vec![],
            }],
        };
        let out = generate(&[site], no_resolver);
        assert!(out.contains("reverse_proxy localhost:8080"));
        assert!(!out.contains("header_up Host"));
    }

    #[test]
    fn parse_target_variants() {
        assert_eq!(
            parse_target("localhost:3000"),
            ParsedTarget {
                scheme: "".into(),
                host: "localhost".into(),
                port: Some("3000".into()),
            }
        );
        assert_eq!(
            parse_target("https://api.example.com"),
            ParsedTarget {
                scheme: "https://".into(),
                host: "api.example.com".into(),
                port: None,
            }
        );
        assert_eq!(
            parse_target("http://a.b.c:8080/some/path"),
            ParsedTarget {
                scheme: "http://".into(),
                host: "a.b.c".into(),
                port: Some("8080".into()),
            }
        );
        // Non-numeric port after ':' should not be parsed as a port.
        assert_eq!(
            parse_target("redis:primary"),
            ParsedTarget {
                scheme: "".into(),
                host: "redis:primary".into(),
                port: None,
            }
        );
    }
}
